# CMake generated Testfile for 
# Source directory: /root/jty/nanomsg-1.0.0
# Build directory: /root/jty/nanomsg-1.0.0
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(inproc "/root/jty/nanomsg-1.0.0/inproc" "5500")
SET_TESTS_PROPERTIES(inproc PROPERTIES  TIMEOUT "5")
ADD_TEST(inproc_shutdown "/root/jty/nanomsg-1.0.0/inproc_shutdown" "5510")
SET_TESTS_PROPERTIES(inproc_shutdown PROPERTIES  TIMEOUT "5")
ADD_TEST(ipc "/root/jty/nanomsg-1.0.0/ipc" "5520")
SET_TESTS_PROPERTIES(ipc PROPERTIES  TIMEOUT "5")
ADD_TEST(ipc_shutdown "/root/jty/nanomsg-1.0.0/ipc_shutdown" "5530")
SET_TESTS_PROPERTIES(ipc_shutdown PROPERTIES  TIMEOUT "30")
ADD_TEST(ipc_stress "/root/jty/nanomsg-1.0.0/ipc_stress" "5540")
SET_TESTS_PROPERTIES(ipc_stress PROPERTIES  TIMEOUT "5")
ADD_TEST(tcp "/root/jty/nanomsg-1.0.0/tcp" "5550")
SET_TESTS_PROPERTIES(tcp PROPERTIES  TIMEOUT "5")
ADD_TEST(tcp_shutdown "/root/jty/nanomsg-1.0.0/tcp_shutdown" "5560")
SET_TESTS_PROPERTIES(tcp_shutdown PROPERTIES  TIMEOUT "120")
ADD_TEST(ws "/root/jty/nanomsg-1.0.0/ws" "5570")
SET_TESTS_PROPERTIES(ws PROPERTIES  TIMEOUT "5")
ADD_TEST(pair "/root/jty/nanomsg-1.0.0/pair" "5580")
SET_TESTS_PROPERTIES(pair PROPERTIES  TIMEOUT "5")
ADD_TEST(pubsub "/root/jty/nanomsg-1.0.0/pubsub" "5590")
SET_TESTS_PROPERTIES(pubsub PROPERTIES  TIMEOUT "5")
ADD_TEST(reqrep "/root/jty/nanomsg-1.0.0/reqrep" "5600")
SET_TESTS_PROPERTIES(reqrep PROPERTIES  TIMEOUT "5")
ADD_TEST(pipeline "/root/jty/nanomsg-1.0.0/pipeline" "5610")
SET_TESTS_PROPERTIES(pipeline PROPERTIES  TIMEOUT "5")
ADD_TEST(survey "/root/jty/nanomsg-1.0.0/survey" "5620")
SET_TESTS_PROPERTIES(survey PROPERTIES  TIMEOUT "5")
ADD_TEST(bus "/root/jty/nanomsg-1.0.0/bus" "5630")
SET_TESTS_PROPERTIES(bus PROPERTIES  TIMEOUT "5")
ADD_TEST(async_shutdown "/root/jty/nanomsg-1.0.0/async_shutdown" "5640")
SET_TESTS_PROPERTIES(async_shutdown PROPERTIES  TIMEOUT "30")
ADD_TEST(block "/root/jty/nanomsg-1.0.0/block" "5650")
SET_TESTS_PROPERTIES(block PROPERTIES  TIMEOUT "5")
ADD_TEST(term "/root/jty/nanomsg-1.0.0/term" "5660")
SET_TESTS_PROPERTIES(term PROPERTIES  TIMEOUT "5")
ADD_TEST(timeo "/root/jty/nanomsg-1.0.0/timeo" "5670")
SET_TESTS_PROPERTIES(timeo PROPERTIES  TIMEOUT "5")
ADD_TEST(iovec "/root/jty/nanomsg-1.0.0/iovec" "5680")
SET_TESTS_PROPERTIES(iovec PROPERTIES  TIMEOUT "5")
ADD_TEST(msg "/root/jty/nanomsg-1.0.0/msg" "5690")
SET_TESTS_PROPERTIES(msg PROPERTIES  TIMEOUT "5")
ADD_TEST(prio "/root/jty/nanomsg-1.0.0/prio" "5700")
SET_TESTS_PROPERTIES(prio PROPERTIES  TIMEOUT "5")
ADD_TEST(poll "/root/jty/nanomsg-1.0.0/poll" "5710")
SET_TESTS_PROPERTIES(poll PROPERTIES  TIMEOUT "5")
ADD_TEST(device "/root/jty/nanomsg-1.0.0/device" "5720")
SET_TESTS_PROPERTIES(device PROPERTIES  TIMEOUT "5")
ADD_TEST(device4 "/root/jty/nanomsg-1.0.0/device4" "5730")
SET_TESTS_PROPERTIES(device4 PROPERTIES  TIMEOUT "5")
ADD_TEST(device5 "/root/jty/nanomsg-1.0.0/device5" "5740")
SET_TESTS_PROPERTIES(device5 PROPERTIES  TIMEOUT "5")
ADD_TEST(device6 "/root/jty/nanomsg-1.0.0/device6" "5750")
SET_TESTS_PROPERTIES(device6 PROPERTIES  TIMEOUT "5")
ADD_TEST(device7 "/root/jty/nanomsg-1.0.0/device7" "5760")
SET_TESTS_PROPERTIES(device7 PROPERTIES  TIMEOUT "30")
ADD_TEST(emfile "/root/jty/nanomsg-1.0.0/emfile" "5770")
SET_TESTS_PROPERTIES(emfile PROPERTIES  TIMEOUT "5")
ADD_TEST(domain "/root/jty/nanomsg-1.0.0/domain" "5780")
SET_TESTS_PROPERTIES(domain PROPERTIES  TIMEOUT "5")
ADD_TEST(trie "/root/jty/nanomsg-1.0.0/trie" "5790")
SET_TESTS_PROPERTIES(trie PROPERTIES  TIMEOUT "5")
ADD_TEST(list "/root/jty/nanomsg-1.0.0/list" "5800")
SET_TESTS_PROPERTIES(list PROPERTIES  TIMEOUT "5")
ADD_TEST(hash "/root/jty/nanomsg-1.0.0/hash" "5810")
SET_TESTS_PROPERTIES(hash PROPERTIES  TIMEOUT "5")
ADD_TEST(stats "/root/jty/nanomsg-1.0.0/stats" "5820")
SET_TESTS_PROPERTIES(stats PROPERTIES  TIMEOUT "5")
ADD_TEST(symbol "/root/jty/nanomsg-1.0.0/symbol" "5830")
SET_TESTS_PROPERTIES(symbol PROPERTIES  TIMEOUT "5")
ADD_TEST(separation "/root/jty/nanomsg-1.0.0/separation" "5840")
SET_TESTS_PROPERTIES(separation PROPERTIES  TIMEOUT "5")
ADD_TEST(zerocopy "/root/jty/nanomsg-1.0.0/zerocopy" "5850")
SET_TESTS_PROPERTIES(zerocopy PROPERTIES  TIMEOUT "5")
ADD_TEST(shutdown "/root/jty/nanomsg-1.0.0/shutdown" "5860")
SET_TESTS_PROPERTIES(shutdown PROPERTIES  TIMEOUT "5")
ADD_TEST(cmsg "/root/jty/nanomsg-1.0.0/cmsg" "5870")
SET_TESTS_PROPERTIES(cmsg PROPERTIES  TIMEOUT "5")
ADD_TEST(bug328 "/root/jty/nanomsg-1.0.0/bug328" "5880")
SET_TESTS_PROPERTIES(bug328 PROPERTIES  TIMEOUT "5")
ADD_TEST(ws_async_shutdown "/root/jty/nanomsg-1.0.0/ws_async_shutdown" "5890")
SET_TESTS_PROPERTIES(ws_async_shutdown PROPERTIES  TIMEOUT "5")
ADD_TEST(reqttl "/root/jty/nanomsg-1.0.0/reqttl" "5900")
SET_TESTS_PROPERTIES(reqttl PROPERTIES  TIMEOUT "10")
ADD_TEST(surveyttl "/root/jty/nanomsg-1.0.0/surveyttl" "5910")
SET_TESTS_PROPERTIES(surveyttl PROPERTIES  TIMEOUT "10")
SUBDIRS(src)
